connection-time: 30 # Number of seconds before a queued user is sent to the back of the queue
view-size: 5 # Number of queued players to show in the status command

discord:
  webhook: "" # An optional Discord webhook to notify users
  events:
    queue-empty: false # The queue is empty
    player-on-clock: false # The current player(s) on the clock
